CREATE DATABASE Health_Care_DB;
USE Health_Care_DB;
SHOW TABLES; 
SELECT * FROM H_C_Table;

-- Data Understanding
-- 1. Show first 10 records.
SELECT * FROM H_C_Table 
ORDER BY PATIENT_NAME ASC LIMIT 10;

-- 2. Count total number of patients.
SELECT COUNT(PATIENT_NAME)  AS TOTAL_NO_OF_PATIENTS 
FROM H_C_Table;

-- 3. List all distinct diseases.
SELECT DISTINCT(MEDICAL_CONDITION) 
FROM H_C_TABLE ;

-- 4. Find minimum, maximum, and average patient age.
SELECT MIN(AGE) AS MIN_AGE, MAX(AGE) AS MAX_AGE, AVG(AGE) AS AVG_AGE 
FROM H_C_TABLE;

-- Filtering (WHERE Clause)
-- 5. List patients diagnosed with 'Diabetes'.
SELECT DISTINCT(PATIENT_NAME), MEDICAL_CONDITION FROM H_C_TABLE 
WHERE MEDICAL_CONDITION = 'DIABETES'
ORDER BY PATIENT_NAME ASC;

-- 6. Find patients admitted after '2023-01-01'.
SELECT DISTINCT(PATIENT_NAME), DATE_OF_ADMISSION FROM H_C_TABLE
WHERE DATE_OF_ADMISSION = '2023-01-01' ;

-- 7. Find female patients above 40 years.
SELECT DISTINCT(PATIENT_NAME) , GENDER FROM H_C_TABLE
WHERE GENDER = 'FEMALE';

-- Aggregation (GROUP BY)
-- 8. 	Count patients by disease.
SELECT MEDICAL_CONDITION AS DISEASE, COUNT(PATIENT_NAME) AS PATIENTS 
FROM H_C_TABLE 
GROUP BY MEDICAL_CONDITION;

-- 9. Find average treatment cost per disease
SELECT MEDICAL_CONDITION AS DISEASE, ROUND(AVG(BILLING_AMOUNT), 2) AS AVG_TREATMENT
FROM H_C_TABLE 
GROUP BY MEDICAL_CONDITION ORDER BY AVG_TREATMENT DESC;

-- 10. Find total revenue generated per hospital.
SELECT DISTINCT(HOSPITAL_NAME), ROUND(SUM(BILLING_AMOUNT), 2) AS TOTAL_REVENUE 
FROM H_C_TABLE
GROUP BY HOSPITAL_NAME 
ORDER BY TOTAL_REVENUE DESC;

-- 11. Find number of patients admitted per year.
SELECT DISTINCT(YEAR), COUNT(PATIENT_NAME) AS TOTAL_PATIENTS  
FROM H_C_TABLE
GROUP BY YEAR 
ORDER BY TOTAL_PATIENTS DESC;

-- Sorting & Ranking
-- 12. Top 5 most expensive treatments.
SELECT BILLING_AMOUNT FROM H_C_TABLE ORDER BY BILLING_AMOUNT DESC LIMIT 5;

-- CASE Statements
-- 13. 
/* Categorize patients:
Age < 18 → 'Child'
18–60 → 'Adult'
60+ → 'Senior' */

SELECT 
	CASE 
		WHEN AGE < 18  THEN 'CHILD'
		WHEN AGE BETWEEN 18 AND 60 THEN 'ADULT'
		ELSE 'SENIOR'
	END AS AGE_CATEGORY, 
    COUNT(*) AS TOTAL_PATIENTS
FROM H_C_TABLE
GROUP BY AGE_CATEGORY;

-- 14. 
/* Categorize treatment cost:
< 20,000 → Low
20,000–50,000 → Medium
50,000 → High*/

SELECT  
CASE 
	WHEN BILLING_AMOUNT < 20000 THEN 'LOW_AMOUNT'
    WHEN BILLING_AMOUNT BETWEEN 20000 AND 50000 THEN 'MEDIUM_AMOUNT'
    ELSE 'HIGH_AMOUNT' 
END AS TREATMENT_COST_CATEGORY, COUNT(*) AS TOTAL_AMOUNT
FROM H_C_TABLE
GROUP BY TREATMENT_COST_CATEGORY ORDER BY TOTAL_AMOUNT DESC;



